const base = import.meta.env.BASE_URL || '/';

export const drumKits = [
  {
    id: 'stock',
    name: 'Stock Kit',
    type: 'synth',
  },
  {
    id: 'boom-bap',
    name: 'Boom Bap',
    type: 'samples',
    samples: {
      kick: `${base}drum-kits/boom-bap/kick.wav`,
      snare: `${base}drum-kits/boom-bap/snare.wav`,
      hihat: `${base}drum-kits/boom-bap/hihat.wav`,
      hihatOpen: `${base}drum-kits/boom-bap/hihatOpen.wav`,
      hihatEdge: `${base}drum-kits/boom-bap/hihatEdge.wav`,
      crash: `${base}drum-kits/boom-bap/crash.wav`,
      ride: `${base}drum-kits/boom-bap/ride.wav`,
    },
  },
  {
    id: 'jungle-classic',
    name: 'Jungle Classic',
    type: 'samples',
    samples: {
      kick: `${base}drum-kits/jungle/classic-kick.wav`,
      snare: `${base}drum-kits/jungle/classic-snare.wav`,
      hihat: `${base}drum-kits/jungle/classic-hihat.wav`,
      hihatOpen: `${base}drum-kits/jungle/classic-hihatOpen.wav`,
      hihatEdge: `${base}drum-kits/jungle/classic-hihatEdge.wav`,
      crash: `${base}drum-kits/jungle/classic-crash.wav`,
      ride: `${base}drum-kits/jungle/classic-ride.wav`,
      tomHi: `${base}drum-kits/jungle/classic-tom-hi.wav`,
      tomMid: `${base}drum-kits/jungle/classic-tom-mid.wav`,
      tomLo: `${base}drum-kits/jungle/classic-tom-lo.wav`,
    },
  },
  {
    id: 'jungle-heavy',
    name: 'Heavy Jungle',
    type: 'samples',
    samples: {
      kick: `${base}drum-kits/jungle/heavy-kick.wav`,
      snare: `${base}drum-kits/jungle/heavy-snare.wav`,
      hihat: `${base}drum-kits/jungle/heavy-hihat.wav`,
      hihatOpen: `${base}drum-kits/jungle/heavy-hihatOpen.wav`,
      hihatEdge: `${base}drum-kits/jungle/heavy-hihatEdge.wav`,
      crash: `${base}drum-kits/jungle/heavy-crash.wav`,
      ride: `${base}drum-kits/jungle/heavy-ride.wav`,
      tomHi: `${base}drum-kits/jungle/heavy-tom-hi.wav`,
      tomMid: `${base}drum-kits/jungle/heavy-tom-mid.wav`,
      tomLo: `${base}drum-kits/jungle/heavy-tom-lo.wav`,
    },
  },
  {
    id: 'jungle-oldschool',
    name: 'Old School Jungle',
    type: 'samples',
    samples: {
      kick: `${base}drum-kits/jungle/oldschool-kick.wav`,
      snare: `${base}drum-kits/jungle/oldschool-snare.wav`,
      hihat: `${base}drum-kits/jungle/oldschool-hihat.wav`,
      hihatOpen: `${base}drum-kits/jungle/oldschool-hihatOpen.wav`,
      hihatEdge: `${base}drum-kits/jungle/oldschool-hihatEdge.wav`,
      crash: `${base}drum-kits/jungle/oldschool-crash.wav`,
      ride: `${base}drum-kits/jungle/oldschool-ride.wav`,
      tomHi: `${base}drum-kits/jungle/oldschool-tom-hi.wav`,
      tomMid: `${base}drum-kits/jungle/oldschool-tom-mid.wav`,
      tomLo: `${base}drum-kits/jungle/oldschool-tom-lo.wav`,
    },
  },
];
